package org.ceedcv.exaprofinal8.modelo;
// Generated 12-may-2016 16:28:58 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    private int idp;
    private String nom;

    Persona() {
    }

    Persona(int idp, String nom) {
        this.idp = idp;
        this.nom = nom;
    }

    public int getIdp() {
        return idp;
    }

    /**
     * @param idp the idp to set
     */
    public void setIdp(int idp) {
        this.idp = idp;
    }

    /**
     * @return the nom
     */
    public String getNom() {
        return nom;
    }

    /**
     * @param nom the nom to set
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    public String toString() {
        return idp + " " + nom;
    }

}
